### ISSUE TITLE
Github deprecated query parameter for token

### ISSUE THREAD

**Issue by negebauer** [joenas/huginn_github_notifications_agent#8]
This gem should use the Authorization HTTP header for getting notifications, since using the access_token query parameter is deprecated.

**Comment by joenas** [comment]
Hey. Yeah I just noticed I got an email regarding that. Bit short on time right now so if you want to submit a Pull request, feel free 🙂

**Comment by negebauer** [comment]
Opened a pr

**Comment by negebauer** [comment]
Got the email again, are you planning on releasing a new version soon?

**Comment by joenas** [comment]
Oh sorry, I forgot about that. I tested it on my instance using the `master` branch like so `ADDITIONAL_GEMS=huginn_github_notifications_agent(github: joenas/huginn_github_notifications_agent)`. I'll try and make a release today :)

**Comment by negebauer** [comment]
Cool :D

**Comment by joenas** [comment]
Now [available](https://rubygems.org/gems/huginn_github_notifications_agent/versions/0.0.2) @negebauer 😄

**Comment by negebauer** [comment]
Nice, will update on my side too
